config:
  clients:
    - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push

extraScrapeConfigs: |
  - job_name: varlogs

    static_configs:
      - targets:
          - localhost

        labels:
          job: varlogs
          __path__: /var/log/*log