adminUser: admin

adminPassword: admin123

initChownData:
  enabled: false

service:
  type: ClusterIP

persistence:
  enabled: true
  type: pvc

  accessModes:
    - ReadWriteOnce

  size: 5Gi

  storageClassName: standard

  finalizers:
    - kubernetes.io/pvc-protection

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local
        isDefault: true

grafana.ini:
  users:
    allow_sign_up: false