loki:
  auth_enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

gateway:
  enabled: false

monitoring:
  dashboards:
    enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

minio:
  enabled: false

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0
